# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Alessandro Antonucci"
description:        "Academic Website"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "alessandroantonucci.me"
author:             "gfjaru"
twitter:
  username:         "gfjaru"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Publications"
    remote:         false
    localpath:      "./publications/"
  - name:           "Scholar"
    remote:         true
    href:           "//scholar.google.lt/citations?hl=it&view_op=list_works&gmla=AJsN-F4NLhgCkr_uc91Wa735D_0wWO8Z0kM1SL_p8D5Am8nL1SjS_aiFKa8bLSO_IB8ILP5mu1RkuPpxgzDm3Yf2b9Ck9bqAsnMvW8L4-wFWQGjZAM2xc5o&user=0uOsJggAAAAJ
github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

scholar:
  style: apa
  bibliography_template: bib
  sort_by: year, month
  order: descending
  reversed: "reversed"
  bibliography_list_attributes:
    reversed: "reversed" # This reverses the numbering of publications in the sorted group.


gems:
  - jekyll-seo-tag
